import {
  ProcurementRequest,
  Supplier,
  ProcurementNotification,
} from "@/types/procurement";
import { SAVED_ADDRESSES } from "./mock-portal-data";

// ─── Supplier Directory ────────────────────────────────────

export const MOCK_SUPPLIERS: Supplier[] = [
  {
    id: "sup-01",
    name: "Toyota Tsusho Parts Japan",
    contact: "Kenji Yamamoto",
    email: "k.yamamoto@toyotatsusho-parts.jp",
    phone: "+81 52 584 5000",
    country: "Japan",
    specializations: ["Toyota", "Lexus", "Genuine OEM"],
    rating: 5,
  },
  {
    id: "sup-02",
    name: "Nagoya Auto Parts Co.",
    contact: "Haruki Tanaka",
    email: "h.tanaka@nagoya-autoparts.co.jp",
    phone: "+81 52 201 3300",
    country: "Japan",
    specializations: ["Toyota", "Honda", "Mazda", "Aftermarket"],
    rating: 4,
  },
  {
    id: "sup-03",
    name: "Pacific Motor Spares AU",
    contact: "Steve Mitchell",
    email: "steve@pacificmotorspares.com.au",
    phone: "+61 3 9876 5432",
    country: "Australia",
    specializations: ["Nissan", "Subaru", "Holden", "Aftermarket"],
    rating: 4,
  },
  {
    id: "sup-04",
    name: "Hiroshima OEM Direct",
    contact: "Yuki Sato",
    email: "y.sato@hiroshima-oem.jp",
    phone: "+81 82 241 8800",
    country: "Japan",
    specializations: ["Mazda", "Genuine OEM", "LED Systems"],
    rating: 5,
  },
  {
    id: "sup-05",
    name: "Bangkok Auto Components",
    contact: "Somchai Prasert",
    email: "somchai@bkkauto.co.th",
    phone: "+66 2 714 2200",
    country: "Thailand",
    specializations: ["Toyota", "Isuzu", "Mitsubishi", "Aftermarket"],
    rating: 3,
  },
];

// ─── Procurement Staff ─────────────────────────────────────

export const PROCUREMENT_STAFF = [
  { id: "staff-01", name: "Sarah Jenkins", role: "Senior Sourcing Specialist" },
  { id: "staff-02", name: "David Vance", role: "Procurement Manager" },
  { id: "staff-03", name: "Elena Rodriguez", role: "Procurement Analyst" },
];

// ─── Procurement Requests (Full Lifecycle Spread) ──────────

export const INITIAL_PROCUREMENT_REQUESTS: ProcurementRequest[] = [
  // ── STATUS: Submitted (New) ──
  {
    id: "req-145",
    requestNumber: "AH-P-000145",
    customerName: "AutoCare Auckland",
    vehicle: {
      make: "Toyota",
      model: "RAV4",
      year: 2022,
      vin: "MXAA54-0018923",
      registration: "RAV422",
      engine: "M20A-FKS (2.0L Dynamic Force)",
      variant: "GX AWD",
      transmission: "CVT",
      driveConfig: "AWD",
    },
    part: {
      name: "Front Brake Disc Rotor Set (Pair)",
      partNumber: "43512-0R080",
      quantity: 1,
      preference: "Genuine OEM",
      condition: "Brand New OEM",
    },
    supporting: {
      notes: "Customer reports disc warping and vibration under braking. Requires genuine rotors for warranty compliance.",
      photos: [],
      documents: [],
    },
    deliveryAddress: SAVED_ADDRESSES[0],
    dateSubmitted: "2026-09-10",
    status: "Submitted",
    assignedStaff: "Unassigned",
    supplierQuotations: [],
    customerQuoteVersions: [],
    internalNotes: [],
    messages: [],
  },

  // ── STATUS: Submitted (New) ──
  {
    id: "req-144",
    requestNumber: "AH-P-000144",
    customerName: "Wellington Fleet Services",
    vehicle: {
      make: "Ford",
      model: "Ranger Wildtrak",
      year: 2023,
      vin: "MNCLBEP00PW301445",
      registration: "FRW230",
      engine: "V6 3.0L EcoBoost",
      variant: "Wildtrak",
      transmission: "10-Speed Auto",
      driveConfig: "4WD",
    },
    part: {
      name: "Rear Diff Lock Actuator Assembly",
      partNumber: "EB3Z-4A626-A",
      quantity: 1,
      preference: "Genuine OEM",
      condition: "Brand New OEM",
    },
    supporting: {
      notes: "Electronic diff lock not engaging. Dashboard warning light active.",
      photos: [],
      documents: [],
    },
    deliveryAddress: SAVED_ADDRESSES[0],
    dateSubmitted: "2026-09-10",
    status: "Submitted",
    assignedStaff: "Unassigned",
    supplierQuotations: [],
    customerQuoteVersions: [],
    internalNotes: [],
    messages: [],
  },

  // ── STATUS: Sourcing ──
  {
    id: "req-138",
    requestNumber: "AH-P-000138",
    customerName: "SP Motors Auckland",
    vehicle: {
      make: "Toyota",
      model: "Land Cruiser Prado",
      year: 2020,
      vin: "GDJ150-004812",
      registration: "LCP401",
      engine: "1GD-FTV (2.8L)",
      variant: "VX Limited",
      transmission: "6-Speed Auto",
      driveConfig: "Full-time 4WD",
    },
    part: {
      name: "KDSS Hydraulic Cylinder Actuator Assembly (Front)",
      partNumber: "48805-60030",
      quantity: 1,
      preference: "Genuine OEM",
      condition: "Brand New OEM",
    },
    supporting: {
      notes: "KDSS warning light active, valve seal failure. Specialist part — dealer-only supply expected.",
      photos: [],
      documents: [],
    },
    deliveryAddress: SAVED_ADDRESSES[0],
    dateSubmitted: "2026-09-09",
    status: "Sourcing",
    assignedStaff: "Sarah Jenkins",
    supplierQuotations: [
      {
        id: "sq-138-01",
        supplierId: "sup-01",
        supplierName: "Toyota Tsusho Parts Japan",
        supplierContact: "Kenji Yamamoto",
        supplierCountry: "Japan",
        supplierPartRef: "48805-60030-TT",
        availability: "Available",
        supplierCost: 820,
        supplierFreight: 95,
        leadTimeDays: 7,
        condition: "Genuine",
        notes: "Factory sealed unit. Requires 5 business days for dispatch from Nagoya.",
        isSelected: false,
        createdAt: "2026-09-09",
      },
    ],
    customerQuoteVersions: [],
    internalNotes: [
      {
        id: "note-138-01",
        author: "Sarah Jenkins",
        text: "Contacted Toyota Tsusho — confirmed availability. Waiting for second quote from Nagoya Auto Parts for comparison.",
        timestamp: "2026-09-09 14:30",
      },
    ],
    messages: [],
  },

  // ── STATUS: Sourcing ──
  {
    id: "req-137",
    requestNumber: "AH-P-000137",
    customerName: "Bay Mechanical Tauranga",
    vehicle: {
      make: "Mitsubishi",
      model: "Triton",
      year: 2021,
      vin: "MMBJNKB40MH018293",
      registration: "TRI210",
      engine: "4N15 2.4L DiD Turbo Diesel",
      variant: "GLS Premium",
      transmission: "6-Speed Auto",
      driveConfig: "4WD",
    },
    part: {
      name: "Transfer Case Assembly with Shift Motor",
      partNumber: "3501A018",
      quantity: 1,
      preference: "Genuine OEM",
      condition: "Brand New OEM",
    },
    supporting: {
      notes: "Transfer case seized after water crossing. Complete unit required with shift motor.",
      photos: [],
      documents: [],
    },
    deliveryAddress: SAVED_ADDRESSES[0],
    dateSubmitted: "2026-09-08",
    status: "Sourcing",
    assignedStaff: "David Vance",
    supplierQuotations: [],
    customerQuoteVersions: [],
    internalNotes: [],
    messages: [],
  },

  // ── STATUS: Quoted (pending customer response) ──
  {
    id: "req-128",
    requestNumber: "AH-P-000128",
    customerName: "AutoCare Auckland",
    vehicle: {
      make: "Toyota",
      model: "Hiace",
      year: 2019,
      vin: "GDH201-0012845",
      registration: "MTB842",
      engine: "1GD-FTV (2.8L Turbo Diesel)",
      variant: "DX / Long Wheelbase",
      transmission: "6-Speed Automatic",
      driveConfig: "RWD",
    },
    part: {
      name: "Left Front Lower Control Arm",
      partNumber: "48069-26150",
      quantity: 1,
      preference: "Genuine OEM",
      condition: "Brand New OEM",
    },
    supporting: {
      notes: "Customer vehicle in hoist bay 2. Bushing torn and ball joint has excessive lateral play. Urgent dispatch requested.",
      photos: [
        "https://images.unsplash.com/photo-1486006920555-c77dce18193b?w=600&auto=format&fit=crop&q=80",
      ],
      documents: ["Fitment_Verification_Hiace_2019.pdf"],
    },
    deliveryAddress: SAVED_ADDRESSES[0],
    dateSubmitted: "2026-09-08",
    status: "Quoted",
    quotedValue: 410,
    assignedStaff: "Sarah Jenkins",
    supplierQuotations: [
      {
        id: "sq-128-01",
        supplierId: "sup-01",
        supplierName: "Toyota Tsusho Parts Japan",
        supplierContact: "Kenji Yamamoto",
        supplierCountry: "Japan",
        supplierPartRef: "48069-26150-TT",
        availability: "In Stock",
        supplierCost: 210,
        supplierFreight: 45,
        leadTimeDays: 5,
        condition: "Genuine",
        notes: "Factory sealed. In stock at Nagoya warehouse.",
        isSelected: true,
        createdAt: "2026-09-08",
      },
      {
        id: "sq-128-02",
        supplierId: "sup-02",
        supplierName: "Nagoya Auto Parts Co.",
        supplierContact: "Haruki Tanaka",
        supplierCountry: "Japan",
        supplierPartRef: "NAP-48069-ALT",
        availability: "In Stock",
        supplierCost: 185,
        supplierFreight: 40,
        leadTimeDays: 8,
        condition: "Aftermarket",
        notes: "Tier-1 aftermarket. IATF 16949 certified manufacturer.",
        isSelected: false,
        createdAt: "2026-09-08",
      },
      {
        id: "sq-128-03",
        supplierId: "sup-05",
        supplierName: "Bangkok Auto Components",
        supplierContact: "Somchai Prasert",
        supplierCountry: "Thailand",
        supplierPartRef: "BAC-48069-26150",
        availability: "Available",
        supplierCost: 165,
        supplierFreight: 55,
        leadTimeDays: 12,
        condition: "Aftermarket",
        notes: "Budget option. 6-month warranty.",
        isSelected: false,
        createdAt: "2026-09-08",
      },
    ],
    selectedQuotationId: "sq-128-01",
    costCalculation: {
      supplierCost: 210,
      supplierFreight: 45,
      autohubMarginPercent: 28,
      autohubMarginAmount: 70,
      customerSellPrice: 325,
      customerFreight: 85,
      totalCustomerQuote: 410,
    },
    customerQuoteVersions: [
      {
        version: 1,
        sellPrice: 325,
        freight: 85,
        totalAmount: 410,
        estimatedTransitDays: 5,
        notes: "Genuine Toyota factory sealed packaging. Backed by 12-month Autohub Trade Warranty.",
        terms: "Standard Autohub Trade Terms. Valid for 5 business days.",
        sentAt: "2026-09-08 16:00",
        status: "Sent",
      },
    ],
    internalNotes: [
      {
        id: "note-128-01",
        author: "Sarah Jenkins",
        text: "Selected Toyota Tsusho (genuine) over aftermarket options. Customer specified OEM preference. 28% margin applied.",
        timestamp: "2026-09-08 15:45",
      },
    ],
    messages: [],
  },

  // ── STATUS: Approved (customer accepted, awaiting payment) ──
  {
    id: "req-125",
    requestNumber: "AH-P-000125",
    customerName: "SP Motors Auckland",
    vehicle: {
      make: "Toyota",
      model: "Hiace",
      year: 2019,
      vin: "TRH200-0089122",
      registration: "NLE591",
      engine: "1TR-FE (2.0L Petrol)",
      variant: "GL High Roof",
      transmission: "Automatic",
      driveConfig: "RWD",
    },
    part: {
      name: "Left Front Lower Control Arm Assembly with Bushing & Ball Joint",
      partNumber: "48069-26140",
      quantity: 1,
      preference: "Genuine OEM",
      condition: "Brand New OEM",
    },
    supporting: {
      notes: "Replacement required for WOF reinspection this Friday.",
      photos: [],
      documents: [],
    },
    deliveryAddress: SAVED_ADDRESSES[0],
    dateSubmitted: "2026-09-07",
    status: "Awaiting Payment",
    quotedValue: 485,
    assignedStaff: "Sarah Jenkins",
    supplierQuotations: [
      {
        id: "sq-125-01",
        supplierId: "sup-01",
        supplierName: "Toyota Tsusho Parts Japan",
        supplierContact: "Kenji Yamamoto",
        supplierCountry: "Japan",
        supplierPartRef: "48069-26140-TT",
        availability: "In Stock",
        supplierCost: 250,
        supplierFreight: 45,
        leadTimeDays: 5,
        condition: "Genuine",
        notes: "Factory unit with ball joint and silent bush.",
        isSelected: true,
        createdAt: "2026-09-07",
      },
    ],
    selectedQuotationId: "sq-125-01",
    costCalculation: {
      supplierCost: 250,
      supplierFreight: 45,
      autohubMarginPercent: 30,
      autohubMarginAmount: 105,
      customerSellPrice: 400,
      customerFreight: 85,
      totalCustomerQuote: 485,
    },
    customerQuoteVersions: [
      {
        version: 1,
        sellPrice: 400,
        freight: 85,
        totalAmount: 485,
        estimatedTransitDays: 5,
        notes: "Genuine Toyota Left Lower Arm Sub-Assembly with bushing and joint.",
        terms: "Standard Autohub Trade Terms. Valid for 5 business days.",
        sentAt: "2026-09-07 14:00",
        status: "Accepted",
      },
    ],
    customerResponse: "Accepted",
    payment: {
      id: "pay-125",
      requestId: "req-125",
      invoiceNumber: "INV-2026-00892",
      amount: 485,
      currency: "NZD",
      status: "Unpaid",
      paymentReference: "AH-P-000125 / INV-00892",
      bankDetails: {
        bankName: "ANZ New Zealand",
        accountName: "Autohub Procurement NZ Ltd",
        accountNumber: "01-0288-0349821-00",
        swiftBic: "ANZBNZ22",
      },
      dueDate: "2026-09-14",
    },
    internalNotes: [
      {
        id: "note-125-01",
        author: "Sarah Jenkins",
        text: "Customer accepted quote v1. Awaiting payment before placing supplier order.",
        timestamp: "2026-09-08 14:20",
      },
    ],
    messages: [],
  },

  // ── STATUS: Awaiting Payment (Quoted, accepted, unpaid) ──
  {
    id: "req-119",
    requestNumber: "AH-P-000119",
    customerName: "Precision Auto Hamilton",
    vehicle: {
      make: "Mazda",
      model: "CX-5",
      year: 2021,
      vin: "KF2P-304910",
      registration: "PRT104",
      engine: "SH-VPTS 2.2L SkyActiv-D",
      variant: "Takami / AWD",
      transmission: "6-Speed Automatic",
      driveConfig: "AWD",
    },
    part: {
      name: "Front Headlamp (LED Projector RHS)",
      partNumber: "KB8B-51-031K",
      quantity: 1,
      preference: "Genuine OEM",
      condition: "Brand New OEM",
    },
    supporting: {
      notes: "Accident repair. LED signature ring and leveling motor must be intact with uncracked tabs.",
      photos: [],
      documents: [],
    },
    deliveryAddress: SAVED_ADDRESSES[1],
    dateSubmitted: "2026-09-05",
    status: "Awaiting Payment",
    quotedValue: 650,
    assignedStaff: "David Vance",
    supplierQuotations: [
      {
        id: "sq-119-01",
        supplierId: "sup-04",
        supplierName: "Hiroshima OEM Direct",
        supplierContact: "Yuki Sato",
        supplierCountry: "Japan",
        supplierPartRef: "KB8B-51-031K-HD",
        availability: "In Stock",
        supplierCost: 380,
        supplierFreight: 65,
        leadTimeDays: 6,
        condition: "Genuine",
        notes: "Genuine Mazda. Bubble-wrapped with custom foam crate.",
        isSelected: true,
        createdAt: "2026-09-05",
      },
      {
        id: "sq-119-02",
        supplierId: "sup-02",
        supplierName: "Nagoya Auto Parts Co.",
        supplierContact: "Haruki Tanaka",
        supplierCountry: "Japan",
        supplierPartRef: "NAP-KB8B-ALT",
        availability: "Available",
        supplierCost: 320,
        supplierFreight: 60,
        leadTimeDays: 10,
        condition: "Aftermarket",
        notes: "Depo brand aftermarket. Compatible but non-OEM.",
        isSelected: false,
        createdAt: "2026-09-05",
      },
    ],
    selectedQuotationId: "sq-119-01",
    costCalculation: {
      supplierCost: 380,
      supplierFreight: 65,
      autohubMarginPercent: 25,
      autohubMarginAmount: 120,
      customerSellPrice: 565,
      customerFreight: 85,
      totalCustomerQuote: 650,
    },
    customerQuoteVersions: [
      {
        version: 1,
        sellPrice: 565,
        freight: 85,
        totalAmount: 650,
        estimatedTransitDays: 6,
        notes: "Mazda OEM Adaptive LED Headlight Unit (Right Hand Side).",
        terms: "Standard Autohub Trade Terms.",
        sentAt: "2026-09-06 10:00",
        status: "Accepted",
      },
    ],
    customerResponse: "Accepted",
    payment: {
      id: "pay-119",
      requestId: "req-119",
      invoiceNumber: "INV-2026-00781",
      amount: 650,
      currency: "NZD",
      status: "Unpaid",
      paymentReference: "AH-P-000119",
      bankDetails: {
        bankName: "ANZ New Zealand",
        accountName: "Autohub Procurement NZ Ltd",
        accountNumber: "01-0288-0349821-00",
        swiftBic: "ANZBNZ22",
      },
      dueDate: "2026-09-10",
    },
    internalNotes: [],
    messages: [],
  },

  // ── STATUS: Ordered (paid, supplier order placed) ──
  {
    id: "req-120",
    requestNumber: "AH-P-000120",
    customerName: "SP Motors Auckland",
    vehicle: {
      make: "Honda",
      model: "Civic Type R",
      year: 2022,
      vin: "FK8-2009141",
      registration: "CTR888",
      engine: "K20C1 Turbo VTEC",
      variant: "FK8 Track Edition",
      transmission: "6-Speed Manual",
      driveConfig: "FWD",
    },
    part: {
      name: "Front Brembo Monobloc 4-Piston Calipers (Pair, Red)",
      partNumber: "45018-TGH-A01",
      quantity: 1,
      preference: "Genuine OEM",
      condition: "Brand New OEM",
    },
    supporting: {
      notes: "Genuine Honda Type R Brembo red calipers.",
      photos: [],
      documents: [],
    },
    deliveryAddress: SAVED_ADDRESSES[0],
    dateSubmitted: "2026-09-02",
    status: "Ordered",
    quotedValue: 1980,
    assignedStaff: "Sarah Jenkins",
    supplierQuotations: [
      {
        id: "sq-120-01",
        supplierId: "sup-02",
        supplierName: "Nagoya Auto Parts Co.",
        supplierContact: "Haruki Tanaka",
        supplierCountry: "Japan",
        supplierPartRef: "NAP-45018-TGH",
        availability: "In Stock",
        supplierCost: 1280,
        supplierFreight: 120,
        leadTimeDays: 7,
        condition: "Genuine",
        notes: "Honda genuine via Nagoya distribution. Factory sealed pair.",
        isSelected: true,
        createdAt: "2026-09-02",
      },
    ],
    selectedQuotationId: "sq-120-01",
    costCalculation: {
      supplierCost: 1280,
      supplierFreight: 120,
      autohubMarginPercent: 30,
      autohubMarginAmount: 480,
      customerSellPrice: 1880,
      customerFreight: 100,
      totalCustomerQuote: 1980,
    },
    customerQuoteVersions: [
      {
        version: 1,
        sellPrice: 1880,
        freight: 100,
        totalAmount: 1980,
        estimatedTransitDays: 7,
        notes: "Genuine Honda Brembo caliper set. 12-month Autohub warranty.",
        terms: "Standard Autohub Trade Terms.",
        sentAt: "2026-09-03 09:00",
        status: "Accepted",
      },
    ],
    customerResponse: "Accepted",
    payment: {
      id: "pay-120",
      requestId: "req-120",
      invoiceNumber: "INV-2026-00810",
      amount: 1980,
      currency: "NZD",
      status: "Paid",
      paymentMethod: "Bank Transfer",
      paymentReference: "AH-P-000120",
      bankDetails: {
        bankName: "ANZ New Zealand",
        accountName: "Autohub Procurement NZ Ltd",
        accountNumber: "01-0288-0349821-00",
      },
      paidAt: "2026-09-10 09:20 NZST",
      dueDate: "2026-09-15",
    },
    supplierOrder: {
      id: "so-120",
      supplierName: "Nagoya Auto Parts Co.",
      supplierRef: "NAP-PO-2026-0891",
      orderDate: "2026-09-10",
      cost: 1400,
      notes: "PO dispatched to Honda Japan central parts warehouse.",
      documents: ["PO-NAP-2026-0891.pdf"],
    },
    internalNotes: [
      {
        id: "note-120-01",
        author: "Sarah Jenkins",
        text: "Payment confirmed. Supplier PO dispatched same day.",
        timestamp: "2026-09-10 09:30",
      },
    ],
    messages: [],
  },

  // ── STATUS: Shipped ──
  {
    id: "req-135",
    requestNumber: "AH-P-000135",
    customerName: "SP Motors Auckland",
    vehicle: {
      make: "Nissan",
      model: "Navara",
      year: 2021,
      vin: "MNTVCPD2300084",
      registration: "NAV321",
      engine: "YS23DDTi Twin Turbo",
      variant: "ST-X 4WD",
      transmission: "7-Speed Auto",
      driveConfig: "4WD",
    },
    part: {
      name: "Garrett Twin Turbocharger Assembly with Electronic Actuator",
      partNumber: "14411-5X01B",
      quantity: 1,
      preference: "OEM Supplier Tier 1",
      condition: "Brand New Certified Aftermarket",
    },
    supporting: {
      notes: "Garrett OEM spec unit acceptable.",
      photos: [],
      documents: [],
    },
    deliveryAddress: SAVED_ADDRESSES[0],
    dateSubmitted: "2026-09-03",
    status: "Shipped",
    quotedValue: 1850,
    assignedStaff: "David Vance",
    supplierQuotations: [
      {
        id: "sq-135-01",
        supplierId: "sup-03",
        supplierName: "Pacific Motor Spares AU",
        supplierContact: "Steve Mitchell",
        supplierCountry: "Australia",
        supplierPartRef: "PMS-14411-5X01B",
        availability: "In Stock",
        supplierCost: 1150,
        supplierFreight: 145,
        leadTimeDays: 5,
        condition: "Aftermarket",
        notes: "Garrett OEM-spec certified aftermarket. Australian warehouse stock.",
        isSelected: true,
        createdAt: "2026-09-03",
      },
    ],
    selectedQuotationId: "sq-135-01",
    costCalculation: {
      supplierCost: 1150,
      supplierFreight: 145,
      autohubMarginPercent: 30,
      autohubMarginAmount: 435,
      customerSellPrice: 1730,
      customerFreight: 120,
      totalCustomerQuote: 1850,
    },
    customerQuoteVersions: [
      {
        version: 1,
        sellPrice: 1730,
        freight: 120,
        totalAmount: 1850,
        estimatedTransitDays: 5,
        notes: "Garrett OEM-spec turbocharger assembly.",
        terms: "Standard Autohub Trade Terms.",
        sentAt: "2026-09-04 10:00",
        status: "Accepted",
      },
    ],
    customerResponse: "Accepted",
    payment: {
      id: "pay-135",
      requestId: "req-135",
      invoiceNumber: "INV-2026-00856",
      amount: 1850,
      currency: "NZD",
      status: "Paid",
      paymentMethod: "Bank Transfer",
      paymentReference: "AH-P-000135",
      bankDetails: {
        bankName: "ANZ New Zealand",
        accountName: "Autohub Procurement NZ Ltd",
        accountNumber: "01-0288-0349821-00",
      },
      paidAt: "2026-09-05",
      dueDate: "2026-09-10",
    },
    supplierOrder: {
      id: "so-135",
      supplierName: "Pacific Motor Spares AU",
      supplierRef: "PMS-PO-2026-1284",
      orderDate: "2026-09-05",
      cost: 1295,
      notes: "Dispatched via Mainfreight Air from Melbourne.",
      documents: ["PO-PMS-2026-1284.pdf"],
    },
    shipment: {
      trackingNumber: "MF-NZ-98234812",
      carrier: "Mainfreight Air & Ocean NZ",
      carrierWebsite: "https://www.mainfreight.com",
      currentMilestone: "Customs Clearance",
      origin: "Tokyo Haneda Gateway (HND)",
      destination: "SP Motors Auckland (Penrose)",
      estimatedDelivery: "Tomorrow, 11 Sep 2026",
      dispatchedAt: "2026-09-06",
      milestonesHistory: [
        {
          milestone: "Received At Shipping Facility",
          location: "Autohub Tokyo Hub, Japan",
          timestamp: "06 Sep • 09:00 AM",
          description: "Consigned to export packaging & barcode scanned",
          isCompleted: true,
        },
        {
          milestone: "In Transit",
          location: "Flight NZ90 / NRT to AKL",
          timestamp: "07 Sep • 06:30 PM",
          description: "Departed Tokyo Narita International Airport",
          isCompleted: true,
        },
        {
          milestone: "Arrived in NZ",
          location: "Auckland International Cargo Terminal (AKL)",
          timestamp: "09 Sep • 07:15 AM",
          description: "Aircraft touched down, cargo transferred to bonded warehouse",
          isCompleted: true,
        },
        {
          milestone: "Customs Clearance",
          location: "NZ Customs & MPI Biosecurity Depot, Auckland",
          timestamp: "Today • 08:30 AM",
          description: "Customs declaration processed. MPI biosecurity clearance in final stage.",
          isCompleted: false,
        },
      ],
    },
    internalNotes: [
      {
        id: "note-135-01",
        author: "David Vance",
        text: "Mainfreight tracking active. Customs clearance expected today.",
        timestamp: "2026-09-10 08:45",
      },
    ],
    messages: [],
  },

  // ── STATUS: Completed ──
  {
    id: "req-110",
    requestNumber: "AH-P-000110",
    customerName: "SP Motors Auckland",
    vehicle: {
      make: "Lexus",
      model: "RX450h",
      year: 2021,
      vin: "GYL25-001924",
      registration: "LEX450",
      engine: "2GR-FXS 3.5L V6 Hybrid",
      variant: "F Sport",
      transmission: "E-CVT",
      driveConfig: "E-Four AWD",
    },
    part: {
      name: "Hybrid Inverter & Power Management Converter Assembly",
      partNumber: "G9200-48190",
      quantity: 1,
      preference: "Genuine OEM",
      condition: "Brand New OEM",
    },
    supporting: {
      notes: "Sealed OEM inverter unit.",
      photos: [],
      documents: [],
    },
    deliveryAddress: SAVED_ADDRESSES[0],
    dateSubmitted: "2026-08-20",
    status: "Completed",
    quotedValue: 3850,
    assignedStaff: "Elena Rodriguez",
    supplierQuotations: [
      {
        id: "sq-110-01",
        supplierId: "sup-01",
        supplierName: "Toyota Tsusho Parts Japan",
        supplierContact: "Kenji Yamamoto",
        supplierCountry: "Japan",
        supplierPartRef: "G9200-48190-TT",
        availability: "In Stock",
        supplierCost: 2400,
        supplierFreight: 200,
        leadTimeDays: 7,
        condition: "Genuine",
        notes: "Factory sealed Lexus/Toyota hybrid inverter unit.",
        isSelected: true,
        createdAt: "2026-08-20",
      },
    ],
    selectedQuotationId: "sq-110-01",
    costCalculation: {
      supplierCost: 2400,
      supplierFreight: 200,
      autohubMarginPercent: 32,
      autohubMarginAmount: 1000,
      customerSellPrice: 3600,
      customerFreight: 250,
      totalCustomerQuote: 3850,
    },
    customerQuoteVersions: [
      {
        version: 1,
        sellPrice: 3600,
        freight: 250,
        totalAmount: 3850,
        estimatedTransitDays: 7,
        notes: "Genuine Lexus hybrid inverter. 12-month Autohub warranty.",
        terms: "Standard Autohub Trade Terms.",
        sentAt: "2026-08-21 09:00",
        status: "Accepted",
      },
    ],
    customerResponse: "Accepted",
    payment: {
      id: "pay-110",
      requestId: "req-110",
      invoiceNumber: "INV-2026-00620",
      amount: 3850,
      currency: "NZD",
      status: "Paid",
      paymentMethod: "Bank Transfer",
      paymentReference: "AH-P-000110",
      bankDetails: {
        bankName: "ANZ New Zealand",
        accountName: "Autohub Procurement NZ Ltd",
        accountNumber: "01-0288-0349821-00",
      },
      paidAt: "2026-08-24",
      dueDate: "2026-08-30",
    },
    supplierOrder: {
      id: "so-110",
      supplierName: "Toyota Tsusho Parts Japan",
      supplierRef: "TT-PO-2026-0678",
      orderDate: "2026-08-24",
      cost: 2600,
      notes: "Delivered and confirmed by customer.",
      documents: ["PO-TT-2026-0678.pdf"],
    },
    internalNotes: [],
    messages: [],
  },
];

// ─── Procurement Notifications ─────────────────────────────

export const INITIAL_PROCUREMENT_NOTIFICATIONS: ProcurementNotification[] = [
  {
    id: "pn-01",
    type: "New Request",
    title: "New Request: AH-P-000145",
    description: "Toyota RAV4 2022 Front Brake Disc Rotor Set submitted by AutoCare Auckland.",
    timestamp: "10m ago",
    read: false,
    requestId: "req-145",
  },
  {
    id: "pn-02",
    type: "New Request",
    title: "New Request: AH-P-000144",
    description: "Ford Ranger 2023 Rear Diff Lock Actuator submitted by Wellington Fleet Services.",
    timestamp: "25m ago",
    read: false,
    requestId: "req-144",
  },
  {
    id: "pn-03",
    type: "Quote Accepted",
    title: "Quote Accepted: AH-P-000128",
    description: "AutoCare Auckland accepted quote for Toyota Hiace control arm at NZ$410.",
    timestamp: "1h ago",
    read: false,
    requestId: "req-128",
  },
  {
    id: "pn-04",
    type: "Payment Received",
    title: "Payment Received: AH-P-000120",
    description: "NZ$1,980.00 confirmed via Bank Transfer. Honda Civic Type R Brembo calipers.",
    timestamp: "2h ago",
    read: true,
    requestId: "req-120",
  },
  {
    id: "pn-05",
    type: "Shipment Update",
    title: "Customs Clearance: AH-P-000135",
    description: "Nissan Navara turbocharger at NZ Customs. Expected release today.",
    timestamp: "3h ago",
    read: true,
    requestId: "req-135",
  },
];
